### ISSUE TITLE
TFX StatisticsGen failing to decode image data

### ISSUE THREAD

**Issue by tall-josh** [tensorflow/tfx#1622]
I've been trying to adapt the TFX Components.ipynb to work with image data, but when I run the `StatisticsGen` I get the following warning for each example:

`WARNING:root:Feature "image/raw" has bytes value "None" which cannot be decoded as a UTF-8 string.` This is causing me two problems. 

1. It floods my Colab cell output causing the notebook to become unresponsive.
2. I guess it's not providing accurate statistics for the image data in my TFExamples.

After some digging, I found where the warning was coming from [_get_unicode_value()](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/statistics/generators/lift_stats_generator.py#L271) in tensorflow/data-validation.

I thought maybe I was encoding the image data incorrectly so I tried an existing cifar-10 [TFRecord](https://github.com/tensorflow/tfx/raw/r0.21.1/tfx/examples/cifar10/data/train.tfrecord) from the tfx repo but encountered the same issue. 

To reproduce:
<a href="https://colab.research.google.com/github/tall-josh/tfx-dingocar/blob/tfx-issue/TFX_dingocar.ipynb" target="_blank"><img src="https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667" alt="Open In Colab" data-canonical-src="https://colab.research.google.com/assets/colab-badge.svg"></a>
I've added the heading **☹ ☹ ☹ ☹ WARNINGS OCCUR HERE ☹ ☹ ☹ ☹** above the offending cell.

**Comment by oscarorti** [comment]
I have the same problem, and I'm also trying to work with my own dataset dealing with the same warning. 

I've tried to encode the image using multiple ways:

```
# 1 
img = tf.io.read_file(filename)
img = tf.io.decode_image(img)
img = tf.io.encode_jpeg(img)

#2
img = tf.io.decode_image(img).numpy().tostring()

#3
img = cv2.imread(filename)
_, jpegVector = cv2.imencode('.jpeg',img)
img = jpegVector.tostring()

#4
img = Image.open(filename).tobytes()

#5
img = open(filename, 'rb').read()
```

None of the options has supressed the warning and the visualization of the statistics is weird. 

I'm trying to add input drift monitoring for image data, is that possible? Or should I extract some image descriptors and monitor the input drift over them (instead of the image)? As I saw in [here](https://medium.com/datadriveninvestor/tensorflow-extended-tfx-data-analysis-validation-and-drift-detection-part-2-6a9c5f8c6210) it is possible to add input drift to a bytes feature, and this is what the image is, a bytes feature. But i'm not sure..

**Comment by tall-josh** [comment]
@oscarorti there is a workaround posted on [Stack](https://stackoverflow.com/questions/60577308/tfx-statisticsgen-for-image-data) but hoping for a "propper' solution

**Comment by nikelite** [comment]
Thank you for reaching out to us. This issue is reported to the TFX team, and we will take a look.

**Comment by embr** [comment]
Hi Folks,

The warnings you are seeing indicate that StatisticsGen is trying to treat your raw image features like a categorical string feature. The image bytes are being decoded just fine. The issue is that when the stats (including top K examples) are being written, the output proto is expecting a UTF-8 valid string, but instead gets the raw image bytes. Nothing is wrong with your setups from what I can tell, but this is just an unintended side-effect of a well-intentioned warning in the event that you have a categorical string feature which can't be serialized. We'll look into finding a better default that handles image data more elegantly.

In the meantime, to tell StatisticsGen that this feature is really an opaque blob, you can pass in a user-modified schema as described in the [StatsGen docs](https://www.tensorflow.org/tfx/guide/statsgen#using_the_statsgen_component_with_a_schema). To generate this schema, you can run StatisticsGen and SchemaGen once (on a sample of data) and then modify the inferred schema to annotate that image features. Here is a modified version of the colab from @tall-josh: 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/gist/embr/3827b641d8afc915ce1545a9956cc107/copy-of-tfx-dingocar.ipynb)

The additional steps are a bit verbose, but having a curated schema is often a good practice for other reasons. Here is the cell that I added to the notebook:

```python
from google.protobuf import text_format
from tensorflow.python.lib.io import file_io
from tensorflow_metadata.proto.v0 import schema_pb2

# Load autogenerated schema (using stats from small batch)

schema = tfx.utils.io_utils.SchemaReader().read(
    tfx.utils.io_utils.get_only_uri_in_dir(
        tfx.types.artifact_utils.get_single_uri(schema_gen.outputs['schema'].get())))

# Modify schema to indicate which string features are images.
# Ideally you would persist a golden version of this schema somewhere rather
# than regenerating it on every run.
for feature in schema.feature:
  if feature.name == 'image/raw':
    feature.image_domain.SetInParent()

# Write modified schema to local file
user_schema_dir ='/tmp/user-schema/'
tfx.utils.io_utils.write_pbtxt_file(
    os.path.join(user_schema_dir, 'schema.pbtxt'), schema)

# Create ImportNode to make modified schema available to other components
user_schema_importer = tfx.components.ImporterNode(
    instance_name='import_user_schema',
    source_uri=user_schema_dir,
    artifact_type=tfx.types.standard_artifacts.Schema)

# Run the user schema ImportNode
context.run(user_schema_importer
```
Hopefully you find this workaround is useful. In the meantime, we'll take a look at a better default experience for image-valued features.

**Comment by tall-josh** [comment]
🚚YES! @embr thank you. I'll give it a go as soon as possible! I'll close this issue afterwards.
