### ISSUE TITLE
Can the BulkInferrer spec be adjusted to also accept a PushedModel channel?

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/tfx#1694]
Currently, the BulkInferrer [expects an optional Model channel](https://github.com/tensorflow/tfx/blob/master/tfx/types/standard_component_specs.py#L49), but it would be nice if it could also accept a `PushedModel` as well, similar to deploying a model for live serving.

**Comment by rose-rong-liu** [comment]
Hi Andrew
  Could you describe the use case a bit? Do you need to chain BulkInferrer after Pusher?
  Thanks

**Comment by andrewsmartin** [comment]
Hi @rose-rong-liu, yes, that is a pretty typical use case for many engineers at Spotify. We have an custom implementation of `Pusher` which writes to an internal metadata store, and it is typical to schedule batch prediction runs when a new `PushedModel` artifact exists. So it would be nice to accept `Union[standard_artifacts.PushedModel, standard_artifacts.Model]`.

**Comment by rose-rong-liu** [comment]
Thanks for the explanation, Andrew! We've filed internal feature request to track this feature.

**Comment by singhniraj08** [comment]
@andrewsmartin,

The current [BulkInferrer](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/BulkInferrer) component consumes a trained model in [SavedModel](https://www.tensorflow.org/guide/saved_model.md) format. Instead of consuming the PushedModel, BulkInferrer can directly consume the model from trainer component. Optionally, BulkInferrer also consumes ModelBlessing produced by a ModelValidator component.

Kindly let us know if this setup helps your use-case. Thank you!

**Comment by singhniraj08** [comment]
@andrewsmartin,

[tfx.v1.extensions.google_cloud_ai_platform.BulkInferrer](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/extensions/google_cloud_ai_platform/BulkInferrer) component is introduced which will push a model to Google Cloud AI Platform, consume examples data, send request to the remote hosted model, and produces the inference results to an external location as PredictionLog proto. After inference, it will delete the model from Google Cloud AI Platform. Let us know if this helps your use-case. Thank you.
