### ISSUE TITLE
BeamDagRunner dependency packaging issues

### ISSUE THREAD

**Issue by redramen** [tensorflow/tfx#1801]
Hi folks, I was attempting to run a TFX pipeline using BeamDagRunner where I was using Dataflow to both orchestrate pipeline and execute the tfx components. However I can't execute the components and my dataflow jobs fail saying setup.py not found. I believe what is happening is my component dataflow jobs are passed the beam pipeline arg `--setup_file=/path/to/setup.py` but that path doesn't exist on the orchestrator dataflow machine, only on my local. Is there a way to where I can pass that in to my component pipeline args properly?

**Comment by aaltay** [comment]
Comment on where this bug is between TFX and Beam:

From the description this does not look like a Beam or Dataflow issue, but rather an issue with the BeamDagRunner in TFX.

IIUC there is a Dataflow job that is started by the BeamDagRunner (the orchestrator job), and this job is in turn attempting to start additional Dataflow jobs however it does not have all the asset in the orchestrator to complete this task. Note that, the second failing Dataflow job is not the culprit here. Two suggestions could be: (i) BeamDagRunner could stage all assets it needs from a local place (local = where the orchestrator program got started) and stage to gcs or a similar location where orchestrator will be running and use those during execution. (ii) Limit BeamDagRunner usage to local runner, where orchestrator executes locally and have access to the same set of assets.

**Comment by sanatmpa1** [comment]
@redramen,

Can you take a look at `Multiple file dependencies` in this [link](https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/) and let us know if it helps? Thanks!

**Comment by sanatmpa1** [comment]
@redramen,

Closing this issue due to lack of recent activity, Please feel free to reopen the issue with more details if the problem still persists. Thanks!
