### ISSUE TITLE
Make `Reshuffle` optional on ExampleGen

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#1907]
Feature request to add an option to disable the Beam Reshuffle step on ExampleGen. 

This steps makes it impossible to use ExampleGen based components for large datasets. Without it, Beam knows how to write to disk after transforming from input format to output format, allowing to transform (slowly) large dataset that would otherwise not fit into memory.

Reference: https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/base_example_gen_executor.py#L66

**Comment by casassg** [comment]
As a followup question, I was wondering, why is this the default behaviour? Is there any reason in particular where reshuffling here is better than reshuffling on the model dataset?

**Comment by zhitaoli** [comment]
The Reshuffle step is distributed (and need not be done in memory) so that shouldn't be an issue.

Dataflow / Flink / Spark would be options for distributed runners. We can provide documentations for how to use these runners, depending on whether you are a GCP user, distributed on prem, or on some other environments.

May I know which runner you are using? Some non-distributed Runner (eg DirectRunner) that operates entirely in-memory?

**Comment by casassg** [comment]
Running on InteractiveContext on prem (DirectRunner). 

We do not have Flink/Spark runner support as of now, but I would like to still run notebooks on my large datasets. 

We will enable more distribute runners (we are also on GCP) but for testing and showing TFX capabilities internally (our current status) it would be nice to have a way to disable this shuffle step as it tries to load the whole dataset on memory when running w DirectRunner. 

I already do shuffle on model training which should largely do a similar effect without the memory constraint, so if I can set this as part of `OutputConfig` that would be great!

**Comment by casassg** [comment]
Resolving as we already have it working w Dataflow at this point
