### ISSUE TITLE
Dependency Hell

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tfx#1987]
It seems that with all these different packages being able to install TFX is not easy at all.
Can we have a meta-package with the full suite (all those values in the table in the README.md) as dependencies? 
This is to avoid spending 1h figuring out the right requirements and save 1000 of hours of engineers across the globe.

These errors might be innocuous but are uncomfortable
```
%%writefile requirements.txt
apache_beam[gcp]==2.21.0
ml-metadata==0.22.0
pyarrow==0.16.0
tensorflow==2.2.0
tensorflow-data-validation==0.22.0
tensorflow-metadata==0.22.0
tensorflow-model-analysis==0.22.1
tensorflow-transform==0.22.0
tfx==0.22.0
```
```
ERROR: ml-metadata 0.22.0 has requirement tensorflow!=2.0.*,!=2.2.0,<3,>=1.15, but you'll have tensorflow 2.2.0 which is incompatible.
```

If the meta package is overkill then just add a set of files with 
`tfx-suite-requirements-0.22.0.txt`

Any other idea?

**Comment by chongkong** [comment]
Hi Mistobaan. Thanks for raising the issue. It will help us prioritizing dependency management in our TFX ecosystem.

Our long term goal is to make `pip install tfx` works, and users don't need to know anything else. This is currently blocked by the lack of dependency resolver in pip, and some minor incompatibility issues we have (with ml-metadata package). So in the end, you will not see the complex compatibility table in the README. We'll not use meta package though.

Meanwhile, having a resolved set (i.e. non-conflicting set) of dependency `requirements.txt` has also been proposed internally, but did not move on, because as a library it is unhelpful and discouraged to pin dependency version ([reading material](https://github.com/Yelp/requirements-tools#our-stance-on-pinning-requirements)). Still, we thought dependency resolution tool is needed, and it is implemented as a setup.py command in master branch (not yet released). In master HEAD, you can get a full list of resolved dependency version by the following command.

```
python setup.py resolve_deps
```

Which would yield the list of requirements.txt. It is not an official feature thus not announced, and be careful on using it directly as a requirements.txt, as it contains non-result string as well. (remove the first line!)

**Comment by chongkong** [comment]
Keeping the issue open until we reach the dependency heaven..

**Comment by ed-alertedh** [comment]
Related to this, I'm trying TFX 0.22.0 with the Beam portable Spark runner and noticed if I use beam 2.21.0 as recommended, the python sdk harness docker image bundles tensorflow 2.1.0 instead of the recommended 2.2.0 https://github.com/apache/beam/blob/v2.21.0/sdks/python/container/base_image_requirements.txt
The end result is I end up with a weird mix of packages if I let TFX manage deploying python packages with sdist. I realise running on spark is probably still a WIP but thought it was worth reporting this.

**Comment by ntakouris** [comment]
Just installed a fresh apache_beam, pyarrow and tfx and managed to run everything both locally and in GCP Dataflow without any issues.

(The only thing was to bump tensorflow from 2.1.0 to latest/2.2.0).

**Comment by chongkong** [comment]
Update: TFX team has investigated this in depth and in 2020 we fixed our release pipeline to correctly handle internal library dependencies (e.g. TFDV, TFMA, BSL, TFT, MLMD). TFX package dependency constraints are set correctly and `pip install` is all you need (as pip is now shipped with dependency resolver, or you can use third party dependency resolvers such as Poetry)

I'm closing this issue now.
