### ISSUE TITLE
Transform pipeline component crashes when no eval split is available

### ISSUE THREAD

**Issue by ntakouris** [tensorflow/tfx#2180]
Transform pipeline component crashes when no eval split is available. Generate a `example_gen_pb2.Output` with only a training split defined, end up with no `eval` directory on the example generation outputs (as expected). Transform component crashes afterwards.

Steps to reproduce:
```python
 example_gen_output_config = example_gen_pb2.Output(
        split_config=example_gen_pb2.SplitConfig(splits=[
            example_gen_pb2.SplitConfig.Split(name='train', hash_buckets=1), # only define train split
        ]))

    example_gen = CsvExampleGen(input=external_input(data_path), output_config=example_gen_output_config)
    components.append(example_gen)

    transform = Transform(
        examples=example_gen.outputs['examples'],
        schema=schema_gen.outputs['schema'],
        preprocessing_fn=preprocessing_fn)
    components.append(transform)
```

Transform component will crash:

```
File "/usr/local/lib/python3.7/site-packages/tfx/types/artifact_utils.py", line 108, in get_split_uri
    'artifacts %s.') % (split, matching_artifacts))
ValueError: Expected exactly one artifact with split 'eval', but found matching artifacts []. [while running 'Run[Transform]']
```

I believe default behaviour for when eval split is missing should be a warning, rather than an error. At least for components that do not require an eval split (like transform).

For now, is there a way to bypass this before a fix is available?

**Comment by ntakouris** [comment]
(besides just duplicating my data CSV to train and eval directories to keep the component quiet)

**Comment by zhitaoli** [comment]
@1025KB and his intern are working on enable more split support in TFX, who may be better comment.

**Comment by 1025KB** [comment]
Currently examplegen's downstream requires `train` and `eval` splits, we are currently working on make it configurable

**Comment by ntakouris** [comment]
@1025KB Not only example gen, but also transform, trainer, evaluator need this kind of functionality. Let engineers choose the way they train and evaluate their models.

**Comment by SMesser-NBCU** [comment]
I haven't been able to find another issue relevant to this, but maybe it's relevant to either an incomplete attempt at renaming Splits or some other bug related to Split names.  I am attempting to upgrade my pipeline from TFX 0.26.0 to TFX 1.0, and that mostly works, but I'm getting a weird issue:
* The Transform component emits records with split names "Split-eval" and "Split-train", as verified by inspecting the Google Storage directory where it's running.
* Trainer then crashes because it is expecting splits named "eval" and "train".  The actual error message is "tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: gs://my-bucket/my-experiment/tfx_pipeline_output/train_debug_tfx1a/transform_multi_label/transformed_examples/18152/train/*'"]
* The Kubeflow UI reports the splits are to be called "eval" and "train" throughout... insofar as I can find references to the split names themselves.
* A glance at [the docs can find a couple examples where output is to "Split-eval" and "Split-train"](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#statisticsgen), but the difference in names isn't discussed explicitly.
* Is there an option to rename splits on either Transform Output or Trainer input?  Could I be reusing a dependency which made sense for TFX 0.26.0 but not for TFX 1.0?

**Comment by SMesser** [comment]
I haven't been able to find another issue relevant to this, but maybe it's relevant to either an incomplete attempt at renaming Splits or some other bug related to Split names. I am attempting to upgrade my pipeline from TFX 0.26.0 to TFX 1.0, and that mostly works, but I'm getting a weird issue:

The Transform component emits records with split names "Split-eval" and "Split-train", as verified by inspecting the Google Storage directory where it's running.
Trainer then crashes because it is expecting splits named "eval" and "train". The actual error message is "tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: gs://my-bucket/my-experiment/tfx_pipeline_output/train_debug_tfx1a/transform_multi_label/transformed_examples/18152/train/*'"
The Kubeflow UI reports the splits are to be called "eval" and "train" throughout... insofar as I can find references to the split names themselves.
A glance at [the docs can find a couple examples where output is to "Split-eval" and "Split-train"](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#statisticsgen), but the difference in names isn't discussed explicitly.
Is there an option to rename splits on either Transform Output or Trainer input? Could I be reusing a dependency which made sense for TFX 0.26.0 but not for TFX 1.0?

**Comment by 1025KB** [comment]
Custom split [guide](https://www.tensorflow.org/tfx/guide/examplegen#custom_inputoutput_split) for ExampleGen
[Split configs](https://www.tensorflow.org/tfx/guide/examplegen#examplegen_downstream_components) for ExampleGen's downstream

**Comment by SMesser** [comment]
Thanks for the links.  I've got a couple things to try now, but the default behavior seems inconsistent:

- I use BigQueryExampleGen with splitting on Input according to specified SQL queries.  The names I specify with example_gen_pb2.Input.Split() are "train" and "eval", but on output they are "Split-train" and "Split-eval" (as verified by inspecting the Google Storage paths)
- The SchemaGen component accepts these outputs from BigQueryExampleGen, but renames them to "train" and "eval" for its own output.
- The Transform component also accepts the outputs from BigQueryExampleGen, but keeps the "Split-train" and "Split-eval" names for its output.
- When I set up the Trainer node, which takes output from both SchemaGen and Transform, I can then choose to either take its inputs as "train" & "eval" _or_ "Split-train" & "Split-eval"

I think the next thing for me to try is specifying an OutputConfig for BigQueryExampleGen, so I can control the names of the output splits, but I don't want it to split the data by hash.  I want it split according to the InputConfig... I'll also see if I can control the names of the splits produced by SchemaGen...

I don't have a minimal, reproducible example ready, but this feels like bugs in BigQueryExampleGen and SchemaGen:  _both_ are renaming splits in ways that are inconsistent with their inputs and explicit configuration.

**Comment by SMesser** [comment]
I worked with this a bit more, and made several changes with the advice of @rcrowe-google : Changing imports to come from `tfx.v1` instead of from `tfx`, where possible, and updating the python dependencies inside the Docker image.  
  
  I was also, for a time,  getting an error message "container_entrypoint.py: error: the following arguments are required:" at Kubeflow container launch.  Fixing the dependencies fixed that too.  (Replacing tfx -> tfx.v1 didn't seem to do much, although it did make it easier to make sure that the imports we were using matched those in the docs and examples.)
  
  Thank you both for the help.

**Comment by ntakouris** [comment]
stale
