### ISSUE TITLE
Make AI Platform Executor for Trainer component support custom Executors

### ISSUE THREAD

**Issue by ColinCampbell-GBI** [tensorflow/tfx#2183]
The AI Platform Executor for the Trainer component is just a wrapper around the normal Trainer Executor. It uses a private method called _GetExecutorClass to get the class it should call once it's running on the AIP. This makes it awkward if we want to run on the AIP, but use a different executor. Currently we can just override the private variable, but that will break some linter checks and seems like a bad idea in general.

I think this function should either be public, or the class should be retrieved from a static variable, to make it consistent with how Component's use the EXECUTOR_SPEC. Either would make it possible to subclass and use a custom executor.

**Comment by 1025KB** [comment]
You can [configure](https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/iris_pipeline_native_keras.py#L123) the executor directly with Trainer component if existing executor doesn't fit your needs

**Comment by ColinCampbell-GBI** [comment]
Yees, I'm currently taking that approach. The issue is that instead of just being able to modify one public part of the AIP executor in a subclass I need to instead make a copy of the entire thing just to modify it safely. This means on version updates I need to re-copy the class to get the latest changes, or risk overriding a private method and having everything just break.

 If the `_GetExecutorClass ` method was public, it would be much simpler for us to use the AIP with a custom executor.

**Comment by ucdmkt** [comment]
@ColinCampbell-GBI Instead of keeping `_GetExecutorClass()` as a private and/or public method, if we canonicalized a way to insert custom Exeuctor class into a Component (like [this](https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_ai_platform/tuner/component.py)), and elevate [underlying utility methods](https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_ai_platform/runner.py) public (which in fact it is currently), which approach would be preferable to you?

===
In either case, I don't have objection to consider _GetExecutorClass()` in current implementation as though a protected method only accessible from subclasses, since Python doesn't have a formal notion of protected method, I believe the convention is to keep `_` prefix and access it from subclasses.

Would it unblock your situation?

**Comment by ColinCampbell-GBI** [comment]
@ucdmkt Yep, that would work. The main issue currently is the inconsistency between Components on how or even if they support overriding the Executor. If all built-in components followed a standard for getting the Executor that allowed overrides, my issue would be resolved.

**Comment by ucdmkt** [comment]
Noted regarding the following point.

> The main issue currently is the inconsistency between Components on how or even if they support overriding the Executor.

\cc @charlesccychen who looks into reconciling it. My understanding to date has been that general direction is to encourage custom componentization easier, rather than the existing pattern of Trainer to allow injecting a custom Executor into existing pre-made Component class. It is the approach [Tuner](https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_ai_platform/tuner/component.py) and [BulkInferrer](https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_ai_platform/bulk_inferrer/component.py) have taken. @charlesccychen can comment on this more.

**Comment by singhniraj08** [comment]
@ColinCampbell-GBI,

Could you please follow this [migration guide](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/launcher/README.md) to migrate from custom launcher to custom ExecutorOperator(a new abstraction in the IR based execution stack) and let us know if it unblocks you.
Thank you!
