### ISSUE TITLE
 Building Container-based components cannot run.

### ISSUE THREAD

**Issue by drzl386** [tensorflow/tfx#2186]
Run the example  Building Container-based components, input as Text or the  data_types.RuntimeParameter. can not compile the pipeline and return the error

TypeError: Object of type InputValuePlaceholder is not JSON serializable

**Comment by 1025KB** [comment]
is there anything in the component spec that is not jsonable?

**Comment by rmothukuru** [comment]
@drzl386,
Can you please respond to @1025KB's comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by vit-** [comment]
@1025KB I have encountered this issue as well. I am trying to run [this example](https://github.com/tensorflow/tfx/blob/4a2671a/tfx/examples/custom_components/container_components/download_grep_print_pipeline.py). The pipeline fails to compile for kubeflow dag runner with the same error @drzl386 mentioned. Although, it compiles with no issues for beam dag runner.

**Comment by vit-** [comment]
It appears that the example does not work with the latest version of TFX published on PyPI (0.22.1) since it lacks [this commit](https://github.com/tensorflow/tfx/commit/4a2671af70921e0357a12174751c3aa3b6d53cdb#). To work around this, I used the nightly build of TFX published as a [Docker image](https://hub.docker.com/r/tensorflow/tfx/tags).
