### ISSUE TITLE
RuntimeParameter ignores zero-valued defaults

### ISSUE THREAD

**Issue by lyschoening** [tensorflow/tfx#2387]
`RuntimeParameter` defaults do not get stored in Kubeflow pipeline package definitions when the default is zero-valued

`foo = data_types.RuntimeParameter('foo', default=0.0, ptype=float)`

Compiles to
```
    pipelines.kubeflow.org/pipeline_spec: >-
      {"inputs": [{"name": "foo"}], "name": "...", ...}
```

Expected would be
```
    pipelines.kubeflow.org/pipeline_spec: >-
      {"inputs": [{"name": "foo", "default": 0.0}], "name": "...", ...}
```

**Comment by numerology** [comment]
I believe the actual issue is that in KFP the default value of parameter is recognized as strings [1]. However when `0.0` or `False` being passed to the constructor [this line](https://github.com/kubeflow/pipelines/blob/f65391309650fdc967586529e79af178241b4c2c/sdk/python/kfp/dsl/_pipeline_param.py#L168) will ignore them.

I can try to put together a fix shortly. Thanks for catching this!


[1] https://github.com/kubeflow/pipelines/blob/f65391309650fdc967586529e79af178241b4c2c/sdk/python/kfp/dsl/_pipeline_param.py#L154
