### ISSUE TITLE
Simplifying configuration of TFX pipelines

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2451]
As a platform maintainer, I would like to easily switch the default configuration for TFX pipelines/runners to some set configuration without having to modify the code and fork the library. 

An example here would be to set the default MLMD connection for pipelines running in a certain Airflow/Kubeflow instance to a centralized hosted service. 

One approach for this would be to add an environment variable that specifies a path which library will look for config file. And then a YAML/JSON file for configuring this default environment.

CC @aoen

**Comment by aoen** [comment]
+1 To Gerard's comment, this is similar to how Airflow does things.
I believe what was suggested previously by Google is e.g. extending the Pipeline class in Gerard's example, but this has several problems:
- Users could experience confusing/breaking behavior if they ever try to copy the import path for the Pipeline class from open source docs
- Users will have less trust of our platform, when they see a different import path for the Pipeline class from open source they may be suspicious that the interface or functionality differs, and may need to spend time finding documentation to understand the differences. This is especially relevant if the user hits an error, they may not know if the error comes from our fork or from the underlying class.
- New optional parameters in TFX pipelines from new TFX releases would silently be ignored and not passed down to the underlying class


Here are some other examples in Airflow of customization/interface points provided to cluster administrators, that may be useful in TFX too in the future although at the moment we don't need them:
- Customizable component parameter defaults at the global level (Airflow only supports this for some like retries/HDFS storage paths but it might be worth considering extending this to include arbitrary primitive parameters or even all types of parameters although it means using a plugin system instead of configuration system which is a lot more complicated)
- Authentication and authorization module: https://airflow.apache.org/docs/stable/security.html#roll-your-own
- Integration with a metrics framework (statsd)
- Resource limits for component executions

**Comment by casassg** [comment]
It would be good to also add a way to load beam_pipeline_args from environment or default location similary
