### ISSUE TITLE
How to pass trainer parameters to modelfile

### ISSUE THREAD

**Issue by yiyinying** [tensorflow/tfx#2703]
I can’t understand the parameter passing, on the official website

**Comment by rmothukuru** [comment]
@yiyinying
Please find the [TFX Trainer Documentation](https://www.tensorflow.org/tfx/guide/trainer) and the  [Example Module File](https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/iris_utils_native_keras.py).

If this doesn't answer your question, can you please elaborate on what exactly you need. Also, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment]
@yiyinying,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
