### ISSUE TITLE
Multiple artifacts from build.yaml

### ISSUE THREAD

**Issue by johnPertoft** [tensorflow/tfx#3020]
Is there a special reason that the tfx cli tool [does not allow](https://github.com/tensorflow/tfx/blob/f8d2544d2815070cf5667910fdc1a0246d239d8c/tfx/tools/cli/container_builder/buildspec.py#L115-L117) multiple (image) artifacts to be built as part of creating/updating a pipeline?

I wanted to have some custom images as part of my pipeline and figured that it would be a good idea to include them there.

**Comment by zhitaoli** [comment]
I would consider this just a feature gap. @charlesccychen can probably comment on if there is any concrete plan to fix this.

Meanwhile, have you checked the image based custom component in [1] and see if that would solve your need?

[1] https://www.tensorflow.org/tfx/guide/container_component

**Comment by johnPertoft** [comment]
Alright thanks! More specifically, it was for running the `Trainer` component with a custom image via the gcp ai-platform executor so I figured I could let tfx/skaffold build this image as well.

**Comment by jiyongjung0** [comment]
Thank you for sharing more information.

I think that it is because tfx CLI assumed the most simple use case, and didn't consider more complicated needs. We need to know which `artifact` is the `target_image` in order to pass it to the pipeline, and we don't have a good way to do it for now. ([--build-target-image is ignored](https://github.com/tensorflow/tfx/blob/f8d2544d2815070cf5667910fdc1a0246d239d8c/tfx/tools/cli/container_builder/builder.py#L72-L77) when there is a build spec file.)

One simple workaround would be using --build-target-image flag to choose an appropriate image in multiple `artifact`s. But I'm afraid that it might be fragile to rely on build.yaml in this way because this use case is not yet considered enough and we might stop using skaffold(and build.yaml) and migrate to other tools (or just docker) in the long term.

**Comment by johnPertoft** [comment]
Alright, fair enough. Thanks!
