### ISSUE TITLE
data_validation are specific to problem type or generic?

### ISSUE THREAD

**Issue by tiru1930** [tensorflow/tfx#3255]
I am looking for tfx data_validation  stasticGen or schemaGen. Does these validation are specific to problem type like tabular data, NLP data, Image Data, I am looking for descriptive statics, but as I can see tfx data validations  loads the data finds out numeric and categorical features and its min,max,mean std and unique, top etc, which are common, like the way we do EDA for tabular data.

**Comment by arghyaganguly** [comment]
@tiru1930 , please mention your possible use case and the custom eda you might want to have/add in data_validation.
Also please provide reproducible code to help us expedite the issue.

Follow the  below links for a code based walk-through on what tfdv offers :

1)natural language statistics  :- [tfdv_nlp](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/statistics/generators/natural_language_stats_generator.py)
2)image statistics :- [tfdv_image](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/statistics/generators/image_stats_generator.py)
3)basic statistics :- [basic stats for tabular data](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/statistics/generators/basic_stats_generator.py)

**Comment by tiru1930** [comment]
@arghyaganguly does this being used when i call 

```
stats = tfdv.generate_statistics_from_csv(data_location="./imdb.csv")

```

**Comment by tiru1930** [comment]
@arghyaganguly @nikelite @zhitaoli , I have not find any reference where i can generate stats on unstructured data i,e NLP and image, Can u please give any references that i can use

**Comment by zhitaoli** [comment]
> @arghyaganguly @nikelite @zhitaoli , I have not find any reference where i can generate stats on unstructured data i,e NLP and image, Can u please give any references that i can use

@davidzats-eng is working on some additional support on this, so we hope to bring more functionalities soon. Maybe stay in tuned and we'll circle back to this thread once we have those functionalities and documentation?

**Comment by singhniraj08** [comment]
Hi @tiru1930,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFX team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFX [version](https://pypi.org/project/tfx/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfx/releases) to stay up to date with the latest developments which are happening in the TFX  space. 
Thank you!
