### ISSUE TITLE
TFLite Rewriter - Pass custom OpsSet options to the converter  

### ISSUE THREAD

**Issue by chris-r-99** [tensorflow/tfx#3342]
**System information** - 
TFX Version (you are using): 0.27.0 
Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Hi, I am using the TFLite Rewriter to convert my model to a Tensorflow Lite model after training. However, I am working with some specific operations that are not included in the standard TFLite OpsSet [OpsSet.TFLITE_BUILTINS]. Meaning I am required to extended the OpsSet of the TFLite Converter by calling: 

```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
```

It would be great if one would be able to pass the supported operations as an argument to the TFLite Rewriter Class. This suggestion would only require 2-3 more lines of code in the TFLite Rewriter Class. (TFLite Target Spec Documentation: https://www.tensorflow.org/lite/api_docs/python/tf/lite/TargetSpec) 

**Will this change the current API? How?**
 No. 

**Who will benefit with this feature?**
All people that want to use the converter to build TFLite Models but need to use operations that are not included in tf.lite.OpsSet.TFLITE_BUILTINS  (many audio or image tasks). 

**Do you have a workaround or are completely blocked by this?** :
The current workaround is to create an own TFLite Rewriter Class and add it to the rewriter factory.

**Comment by deutranium** [comment]
Hi!
If no one is working on this issue, I can take it up. 
Please let me know, thanks :)

cc @chris-r-99 @arghyaganguly @hj929

**Comment by zhitaoli** [comment]
@davidzats-eng To confirm no one is working on this.

**Comment by davidzats-eng** [comment]
Yes, work on this is currently not scheduled.

**Comment by deutranium** [comment]
Cool thanks! I will start working on this :)

**Comment by deutranium** [comment]
Hi!
If I'm not wrong, [this](https://github.com/tensorflow/tfx/blob/489aa43cb96bb3764d570667d646f7ecaeb23521/tfx/components/trainer/rewriting/tflite_rewriter.py#L256) is the part which should be modified accordingly right?
My current thought process is as follows:
- Check if the `quantization_supported_types` is `None` in the `if` condition [here](https://github.com/tensorflow/tfx/blob/489aa43cb96bb3764d570667d646f7ecaeb23521/tfx/components/trainer/rewriting/tflite_rewriter.py#L98)
- If yes, instead of setting its value as `[]`, we can set it as `[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]`
- Since this variable is the one being passed as `converter.target_spec.supported_types` for the TFLiteRewriter class, the required changes would be reflected
- The above steps would be followed by all the tests to ensure that the changes work as expected

Since this is my first time contributing for tfx, please let me know if anything else should be done.

Thanks!!

**Comment by chris-r-99** [comment]
@deutranium Hi! I am not sure why setting `quantization_supported_types` is related to modifying the operation set `target_spec.supported_ops`? I am referring to the operation set that should be modified by e.g. setting `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]` and not `converter.target_spec.supported_types`. (https://www.tensorflow.org/lite/api_docs/python/tf/lite/TargetSpec).  So I would assume you need a new argument with which a custom operation set can be passed to the rewriter class and not modify the existing supported types setup. :)

**Comment by deutranium** [comment]
Hey @chris-r-99 !
Oh okay yes that makes sense. Cool on it!
Thanks!

**Comment by singhniraj08** [comment]
@chris-r-99,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
