### ISSUE TITLE
[Discussion] Making TFX transitive dependencies more flexible

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#3593]
This is mostly a starter discussion to make TFX transitive dependencies more flexible.

Currently it's either an install all (TFT, TFMA, TFDV...) or none (and no pre-built components ml-pipelines-sdk). 

This makes it hard to adopt TFX partially, as you need to have all the deps if you want to use any of the TFX components (even if you just want to use the Trainer, you need all TFT, TFMA, TFDV).

The proposal would be to instead allow customers to specify what modules do we want to use when installing TFX. Something like:

```
# Want to use TFDV, TFT but not TFMA
pip install tfx[tfdv,tft]
# Want to use only tfma
pip install tfx[evaluator]
# Want to use Tuner
pip install tfx[tuner]

# want to use current tfx
pip install tfx[full]
```

I know this may be complex, but would help reduce the footprint of some TFX deployments and allow us to have more fine-grained control over what do we need to execute a component.

**Comment by casassg** [comment]
CC @rcrowe-google  for Twitter label (if possible)

**Comment by chongkong** [comment]
Hi @casassg. As you understand, splitting dependencies into multiple extra dependencies is not trivial. Also one of the reasons we introduced `ml-pipeline-sdk` (light dependencies), instead of moving heavy dependencies into `tfx[full]` and keeping `tfx` light, was to prevent breaking behavior on `pip install tfx`.

Being said that, we want to tackle problem first not the solution first, so it would be great if you can share difficulties you have for tfx package being too heavy.

**Comment by casassg** [comment]
@chongkong that makes sense. I think currently the biggest limitation I see is that I cant use Trainer (and the AI Platform integration) outside TF 2.4 due to a constraint in TFT. If I just want to use Trainer, I should be able to use it without the needed constraint from TFT. 

Right now, I need to either tweak the transitive closure to allow TF 2.3 and compile the wheel manually or write a full custom component since the code is not included on ml-pipelines-sdk wheel.

Another issue is that I cant use ExampleGen and Trainer without also having to bring in TFMA and TFT (and all their transitive constraints) which limit me on what version of libraries I can use to develop other components.  Apart from transitive closure, it's also an issue on docker image size. All the TFX ecosystem libraries add quite a bit of weight to the image, without much optionality. 

Another issue, is that if I want to compile my pipeline into Airflow or Kubeflow, currently, I have to bring all the dep tree from TFX, Even if I dont want to use TFT or TFMA...

An alternative, is to add the source code into ml-pipelines-sdk and make the gradual in ml-pipelines-sdk instead `pip install ml-pipelines-sdk[tfdv,tft]` we would be fine w this. Issue w the current model is that its too much all of nothing, which makes it hard. ml-pipelines-sdk main sell point is integration to MLMD, but I have to vendor a bunch of code if I want to reuse partially tfx codebase.

**Comment by chongkong** [comment]
Thank you @casassg! Let me summarize each item and try to respond to some..

1. Cannot use non-latest TF: The biggest reason tfx (and its dependent libs) narrowly supports the TF version is heavily due to the TFT using the unstable internal API of TF. Currently suggested way is to use the past versions of TFX, but as long as TFX depends on TFT, it will not be able to support broader versions of TF anytime soon. (tfx officially supports two version: the latest TF1 and the latest TF2) Our test environment matrix also only consists of latest TF1 and latest TF2 only.
2. Transitive dependency constraints: If you can give us the name of specific third party libraries that transitive TFX constraints is too tight, we can consider relaxing it as well. Please give us the name!
3. Docker size becomes too large: If it really matters, one workaround for this is to make a modified wheel for tfx with stripped out dependencies: `pip wheel --no-deps tfx` command gives you the tfx wheel file. If you unzip it with `wheel unpack tfx-blah.whl`, you can see its METADATA file, and you can remove unnecessary dependencies, say TFMA, by removing the line `Requires-Dist: tensorflow-model-analysis...`, and then zip it again with `wheel pack ./dir`. The resulting patched tfx wheel no longer depends on TFMA 😅. We cannot publish this wheel officially, but you can make it by your own.
4. Compiling pipeline brings unnecessary deps: AFAIK, `ml-pipeline-sdk` was devised to mitigate this exact issue, and I believe you can compile pipeline with `ml-pipeline-sdk` only? If not, please tell us.
