### ISSUE TITLE
function import from `import_utils.import_func_from_source` not working in dataflow job

### ISSUE THREAD

**Issue by daikeshi** [tensorflow/tfx#3772]
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version:
- TFX Version: 0.27
- Python version: 3.6
- Python dependencies (from `pip freeze` output): cherry-pick a few relevant ones
apache-beam==2.27.0
dill==0.3.1.1

**Describe the current behavior**
We have a custom component that uses `import_utils.import_func_from_source` from `tfx.utils` to import a function in a user module for a dataflow job. The code is roughly looks as follows:
```
predicate_fn = import_utils.import_func_from_source
with self._make_beam_pipeline() as pipeline:
     pipeline | beam.PTransform(predicate_fn)
```
After we bump to TFX 0.27, this custom component stops working and we see the following error in our dataflow job:
```shell
021-05-17 19:27:52.594 EDTError message from worker: Traceback (most recent call last): File 
"/usr/local/lib/python3.6/site-packages/apache_beam/internal/pickler.py", line 290, in loads return dill.loads(s) File 
"/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 275, in loads return load(file, ignore, **kwds) File 
"/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 270, in load return Unpickler(file, ignore=ignore, **kwds).load() File 
"/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 472, in load obj = StockUnpickler.load(self) File 
"/usr/local/lib/python3.6/site-packages/dill/_dill.py", line 462, in find_class return StockUnpickler.find_class(self, module, 
name) ModuleNotFoundError: No module named 'user_module_0' During handling of the above exception, another 
exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.6/site-
packages/dataflow_worker/batchworker.py", line 649, in do_work work_executor.execute() File "/usr/local/lib/python3.6/site-
packages/dataflow_worker/executor.py", line 179, in execute op.start() File "apache_beam/runners/worker/operations.py", 
line 710, in apache_beam.runners.worker.operations.DoOperation.start File "apache_beam/runners/worker/operations.py", 
line 712, in apache_beam.runners.worker.operations.DoOperation.start File "apache_beam/runners/worker/operations.py",
 line 713, in apache_beam.runners.worker.operations.DoOperation.start File "apache_beam/runners/worker/operations.py", 
line 311, in apache_beam.runners.worker.operations.Operation.start File "apache_beam/runners/worker/operations.py", line 
317, in apache_beam.runners.worker.operations.Operation.start File "apache_beam/runners/worker/operations.py", line 659,
in apache_beam.runners.worker.operations.DoOperation.setup File "apache_beam/runners/worker/operations.py", line 660, 
in apache_beam.runners.worker.operations.DoOperation.setup File "apache_beam/runners/worker/operations.py", line 292, 
in apache_beam.runners.worker.operations.Operation.setup File "apache_beam/runners/worker/operations.py", line 306, in 
apache_beam.runners.worker.operations.Operation.setup File "apache_beam/runners/worker/operations.py", line 799, in 
apache_beam.runners.worker.operations.DoOperation._get_runtime_performance_hints File "/usr/local/lib/python3.6/site-
packages/apache_beam/internal/pickler.py", line 294, in loads return dill.loads(s) File "/usr/local/lib/python3.6/site-
packages/dill/_dill.py", line 275, in loads return load(file, ignore, **kwds) File "/usr/local/lib/python3.6/site-
packages/dill/_dill.py", line 270, in load return Unpickler(file, ignore=ignore, **kwds).load() File "/usr/local/lib/python3.6/site-
packages/dill/_dill.py", line 472, in load obj = StockUnpickler.load(self) File "/usr/local/lib/python3.6/site-
packages/dill/_dill.py", line 462, in find_class return StockUnpickler.find_class(self, module, name) ModuleNotFoundError: 
No module named 'user_module_0'
``` 

**Describe the expected behavior**
The imported function should work in dataflow job

**Name of your Organization (Optional)** 
Spotify

**Comment by charlesccychen** [comment]
Hi @daikeshi, could you detail how this worked for your use case before 0.27, and also describe how the overall flow is intended to work for your custom component?  Because of the interaction between Beam user code serialization and imported user modules, I don't think this should have worked in prior versions of TFX either (are you otherwise packaging your user code and pushing it as a Beam `--extra_package`?).  In any case, for Dataflow, the user module needs to be staged via an `--extra_package` argument pointing to a built wheel or source distribution.  You would need to build this wheel, and the recommended way before TFX 0.30 is to do direct imports (not with `import_utils.import_func_from_source`) so that the module names match up when imported by the Python worker on Dataflow.

As of TFX 0.30, we have extra internal utilities to improve this user module use case, but I want to emphasize that these are currently private APIs and are not yet stable.  You can see the usage in https://github.com/tensorflow/tfx/commit/baccb6bc9650aa8f69548e8ca68473e83606f10b and https://github.com/tensorflow/tfx/commit/10e9e8de1d841748dda77ac012092de9bd42ef4b.  Here, there is an internal mechanism for building these user code wheels from module files, which are subsequently picked up as `--extra_package`s for Beam (see the logic in the Beam-based component executors).  Could we also understand your flow a little better?  Is the idea that a reusable component is written that allows instances to be created with module files available?  Is this within a containerized environment, and are these containers used as custom images for Dataflow?

CC: @zhitaoli

**Comment by daikeshi** [comment]
Thanks @charlesccychen for the explanation! That makes sense. I was suspecting that this`import_utils.import_func_from_source` might not be intended to load the user function for the beam job. 

In this specific case, the same function from TFX <= 0.22.2 worked for us but stopped working after we upgraded TFX to 0.27. I think we will need to look into using `--extra_package` in the future. 

> Could we also understand your flow a little better? Is the idea that a reusable component is written that allows instances to be created with module files available? 

Yes, exactly. Our component takes a module file as input similar to `preprocessing.py` in `Transform` component, so users can define UDFs to be used in the dataflow job triggered by this component, e.g. defining a predicate function with specific filtering logic when reading the data in the dataflow job. If TFX can provide an easier standard way to package user module file and pass it dataflow job as `--extra_package`, it will definitely help us here.  

> Is this within a containerized environment, and are these containers used as custom images for Dataflow?

Yes, it's in a containerized environment on KFP, but they are not used as custom images for Dataflow.

**Comment by axelborja** [comment]
I'm facing exactly the same issue, with the TFX version 0.30.0.

**Comment by daikeshi** [comment]
@axelborja in our case, we had to copy/paste the implementation from TFX 0.22.2 in our own library as a workaround. Hope it helps. The new implementation seems to have a serialization issue when it's used on dataflow workers.

**Comment by charlesccychen** [comment]
Hi @axelborja, we are having some more extensive discussion of this issue in https://github.com/tensorflow/tfx/issues/3761.  Can we get a better sense of your environment?  Which runner are you using, and are you disabling the user code wheel packaging logic because you've encountered issues?

Re @daikeshi: this may be a related but different problem from what @axelborja mentions.  We discussed this briefly before, but it would be great to understand the type of user code avoids this in 0.22.2 but broke recently, since I don't recall us doing any special handling for this before.

**Comment by entrpn** [comment]
Same issue here with tfx 1.0.0 and dataflow when using Transforms component.

**Comment by abhishekasingh** [comment]
I facing the same issue with TFX version: 1.0.0
I am trying to run the code on vertex ai pipeline.

force_tf_compat_v1=True didn't worked for me.

Is there any other possible workaround.

**Comment by hasanrafiqatgoogle** [comment]
issue is still there even in 1.5.0

**Comment by rcrowe-google** [comment]
Is this still an issue?  We have had many pipelines running on KF/Dataflow since before 1.0.0, using module files to load the Transform preprocessing_fn code.  One thing to maybe watch for is that if the file is not in the local filesystem on the K8s node it will try to copy it from the URI - for example, from GCS - which means that it needs to have access.
