### ISSUE TITLE
How to use TensorFlow Data Validation (TFDV) in serving to detect anomalies in data.

### ISSUE THREAD

**Issue by axeltidemann** [tensorflow/tfx#3792]
TFX 0.27.0. I am trying to do exactly as described here: https://cloud.google.com/architecture/analyzing-and-validating-data-at-scale-for-ml-using-tfx#anomalies_in_data_format. I have edited the schema generated by SchemaGen for a given feature so it needs to have a minimum value:
```
feature {     
  name: "delay"
  type: FLOAT 
  float_domain {
    min: 1000.0
  }           
  presence {  
    min_fraction: 1.0
    min_count: 1
  }           
  shape {     
    dim {     
      size: 1 
    }         
  }           
} 
```
I can see that it is successfully incorporated into the Transform graph:
```
gsutil cat gs://path/to/Transform/transform_graph/NUMBER/metadata/schema.pbtxt
```
However, when I `curl` the endpoint with a number less then 1000, nothing happens. I would like it to throw an error similar to when you input an unknown categorical value. How can I achieve that?

**Comment by singhniraj08** [comment]
@axeltidemann,

You can get your manual schema and use `tfdv.validate_examples_in_tfrecord` to [check for errors on per-example basis](https://www.tensorflow.org/tfx/data_validation/get_started#checking_for_errors_on_a_per-example_basis) and once this check is passed, then send the data to TF Serving for predictions.

Thank you!

**Comment by axeltidemann** [comment]
@singhniraj08 that is possible, but I prefer a solution where this is part of the TFX graph itself, and not another layer before TensorFlow Serving.

**Comment by singhniraj08** [comment]
@axeltidemann,

Currently, TFDV allows Anomaly detection to identify anomalies, such as missing features, out-of-range values, or wrong feature types and anomalies viewer so that you can see what features have anomalies and learn more in order to correct them. We cannot map TFDV in TF model graph to detect and report back anomaly, but we can implement Transform in TF model graph to transform the incoming serving data to desirable state.

Can this on going feature issue [serving/663](https://github.com/tensorflow/serving/issues/663) in TF Serving help you. You can pass a custom python function in TF Serving to report back anomaly. Let me know if this works and we can discuss the implementation of the feature internally.
Thank you!

**Comment by axeltidemann** [comment]
In a bigger picture, that seems to be a good fit. I will close this issue, and follow the other.
