### ISSUE TITLE
Specify Docker images for components independently

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/tfx#3994]
**System information**

- TFX Version (you are using): 1.0.0rc1
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): MacOS
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

When using Kubeflow Pipelines, it seems that we can only specify Docker image for TFX component here by `default_image`:
https://www.tensorflow.org/tfx/api_docs/python/tfx/orchestration/kubeflow/v2/kubeflow_v2_dag_runner/KubeflowV2DagRunnerConfig

That is, we have to use same image for all components.

**Will this change the current API? How?**

I think it would be nice if we can use different images for different components, for example:

```python
from tfx.v1.components import Trainer

trainer_component = Trainer(
    ...,
    image="gcr.io/trainer/image",
)
```

**Who will benefit with this feature?**

Especially, `Trainer` component typically have complicated dependencies. It is useful to specify different image for it.

**Do you have a workaround or are completely blocked by this?** :

Currently, I use same image for all components.

**Name of your Organization (Optional)**

**Any Other info.**

**Comment by 1025KB** [comment]
Hi, Currently we don't have any way to setup per component image, will keep this as a feature request.

As most component are env agnostic, we might not be able to add image as exec_properties in component.
An alternative might be passing a dict of component name -> image in KFPV2DagRunnerConfig, and we can set image differently [here](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/v2/pipeline_builder.py#L120)

Also a short workaround is you can directly modify the trainer's image in output json file ([example](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/v2/testdata/expected_full_taxi_pipeline_job.json#L73)) before upload that to Vertex

**Comment by AseiSugiyama** [comment]
AFAIK, currently, there are two ways to specify container images for each component in TFX. The first one is limited to a subclass of `BaseBeamComponent` on `Dataflow`. The second one is building KFP pipeline instead of TFX pipeline.

### TFX component with Dataflow

IMO, there is experimental implementation to specify the container image per component inherited from [BaseBeamComponent](https://www.tensorflow.org/tfx/api_docs/python/tfx/dsl/components/base/base_beam_component/BaseBeamComponent). Because Cloud Dataflow has `--worker_harness_container_image` to specify [custom container image](https://cloud.google.com/dataflow/docs/guides/using-custom-containers), subclasses of `BaseBeamComponent` such as `ExampleGen` can be set up with their container image.

I think we could specify container image for each subclass of `BaseBeamComponent` by creating `beam_pipeline_args `, passing it into [`with_beam_pipeline_args`](https://www.tensorflow.org/tfx/api_docs/python/tfx/dsl/components/base/base_beam_component/BaseBeamComponent#with_beam_pipeline_args) and running it on Dataflow, but I have not tested it yet.

### Building KFP pipeline with TFX component

We can specify container images for each component when building pipelines with [Kubeflow Pipelines SDK](https://kubeflow-pipelines.readthedocs.io/en/stable/). There is an implementation [tfx.orchestration.kubeflow.base_component.BaseComponent](https://www.tensorflow.org/tfx/api_docs/python/tfx/orchestration/kubeflow/base_component/BaseComponent) to convert TFX component into KFP component so that we can use TFX components in KFP pipelines. There is `tfx_image` argument to specify the container image for each component, so perhaps we can specify the container image for each component in this way.

I have not tested this way too.

**Comment by ConverJens** [comment]
@1025KB This seems like a good enough solution for our use case! Passing a dict as an override to the base image would be great. That way one could just choose to override the image used just for the desired components, say  Trainer, with minimal config.
