### ISSUE TITLE
KubeflowDagRunner checks whether module_file exists on local machine compiling the pipeline.

### ISSUE THREAD

**Issue by nielsgroen** [tensorflow/tfx#4019]
- TensorFlow version: 2.5.0
- TFX Version: 1.0.0rc1
- Python version: 3.7

I am trying to compile a pipeline using the KubeflowDagRunner:
```python3
from tfx.orchestration.kubeflow import kubeflow_dag_runner

kubeflow_dag_runner.KubeflowDagRunner(
                            config=runner_config,
                            output_filename=_output_pipeline_filename).run(
                                _create_pipeline(
                                    pipeline_name=_pipeline_name,
                                    pipeline_root=_pipeline_root,
                                    module_file=_module_file,
                                    serving_model_dir=_serving_model_dir,
                                    # 0 means auto-detect based on on the number of CPUs available
                                    # during execution time.
                                    direct_num_workers=0))
```
This pipeline uses a module file for the Trainer component and the Transform component.

**The current behavior**
Currently in udf_utils.py it is checked whether the module file exists on the machine on which the pipeline is compiled, when compiling the pipeline to a yaml file.

udf_utils.py line 139:
```python3
    elif not fileio.exists(module_file):
      raise ValueError(
          'Specified module file %r for component %s does not exist.' %
          (module_file, self.component))

```

**The expected behavior**
But, I want to upload the .tar.gz file (containing only a yaml file) to our Kubeflow server (a different machine), which contains the specified module file.

So the module_file is not on my local machine, and I don't think it should be. Since the module_file should exist when running the pipeline in Kubeflow, not my windows machine creating the yaml.

**Comment by charlesccychen** [comment]
Hi @nielsgroen, thank you for this report. Can we better understand your workflow for which components you are using, how you are building these images, and where the module file will be loaded from when running on KFP? We made this change to make management of user module files more uniform across different runners, and the current logic handles staging of this user module file as a wheel file written to under the pipeline root, and being passed on to Apache Beam / Dataflow. The current plan is to have this module file be more integrated into the container image build process. Are you using the TFX CLI to build your container image? Also, are you using a hosted KFP deployment, or is this on-premise, and in either case, what filesystem are you using for your pipeline root?

You can find a more detailed explanation of the issue here:

[1] https://github.com/tensorflow/tfx/issues/3761#issuecomment-854729990
[2] https://github.com/tensorflow/tfx/issues/3761#issuecomment-855337123

As a temporary workaround that will break in a future release, you can set the environmental variable `UNSUPPORTED_DO_NOT_PACKAGE_USER_MODULES=1`, but keep in mind this will break usage of the Transform component if you do not also set the argument `force_tf_compat_v1=True`.

**Comment by arghyaganguly** [comment]
@nielsgroen , closing this issue as there has been no response for sometime now.Please feel free to reopen it if required.Thank you.
