### ISSUE TITLE
Cannot find documentation on creating two vocabularies using tft.compute_and_vocabulary() for building seq2seq architectures that need two different input vocabularies

### ISSUE THREAD

**Issue by microcoder-py** [tensorflow/tfx#4096]
Thank you for submitting a TFX documentation issue. Per our GitHub policy, we
only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub and we welcome external contributions!

The TFX docs are open source! To get involved, please read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/guide

### Clear description:

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,

https://www.tensorflow.org/tfx/guide/examplegen

### Request visuals, if applicable

Are there currently visuals? If so, do they look correct? If not, will it
clarify the content?

**Comment by microcoder-py** [comment]
Hi, any update?

**Comment by zoyahav** [comment]
Could you please expand on what it is you're looking to achieve within your preprocessing?

**Comment by microcoder-py** [comment]
Let’s say I’m performing an English to Spanish neural machine translation using Transformers. On the encoder side, I need token mapping for English words to English indices, but on the decoder side, I need a second tokeniser layer, which maps Spanish tokens to indices, and back. I could not find a clear example to do this. The IMDB example uses a single tokenisation layer, which can be done using tft.vocabulary(), but I tried different experiments on using it for multiple, it didn’t work, and I couldn’t find any docs either

**Comment by zoyahav** [comment]
So your questions is about how to do this during modelling (in the trainer), correct?
Since computing different vocabularies for different features can be done by just calling tft.vocabulary/tft.compute_and_apply_vocabulary for each feature.

**Comment by microcoder-py** [comment]
I did do that, but when I ran it for my second feature it just gave all tokens the same ID. Am I doing it wrong? Also, assuming I can do this, how do I get the vocabulary in my model trainer? (To find the word given a predicted token id)

**Comment by microcoder-py** [comment]
Went through the documentation again. From my understanding, TF Transform library does not create any tensorflow ops, only a computation graph for any new input being added, and all the analyser functions perform a full pass over the complete dataset. In effect, this would imply that I can find the indices for every token from TFT, but once done, I cannot get like a preprocessing layer from TFT. If this is correct, then TFT is likely not the right library for me. If not, please correct me. I am yet new to TFX

**Comment by zoyahav** [comment]
Transform should not be giving another feature the same IDs if it computed different vocabularies for each feature.
Transform does add TF ops to the input handling graph which are used to preprocess your data.

Please take a look at the following example: https://www.tensorflow.org/tfx/tutorials/transform/census#preprocessing_with_tftransform
Here you can see that each feature in `CATEGORICAL_FEATURE_KEYS` gets its own vocabulary, and the vocabulary is then looked up as part of the data preprocessing logic since `tft.compute_and_apply_vocabulary` is used.
Alternatively, this example could have used `tft.vocabulary` to not use Transform's logic for applying the vocabularies.

Then in the trainer, the Transform logic and vocabularies can be accessed using `TFTransformOutput`, see example here (under `_input_fn`):
https://www.tensorflow.org/tfx/tutorials/tfx/penguin_tft#run_fn

Let me know if you have any further issues, feel free to attach a notebook showcasing an issue so that we can take a look.

**Comment by microcoder-py** [comment]
Tested again, it worked, I was using it incorrectly. Thank you for the support!
