### ISSUE TITLE
Force Evaluator blessing.

### ISSUE THREAD

**Issue by axeltidemann** [tensorflow/tfx#4390]
**System information**

- TFX Version (you are using): 1.2.0
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): Google Cloud
- Are you willing to contribute it (Yes/No): Yes.

**Describe the feature and the current behavior/state.**
When developing a pipeline I have experienced these scenarios, which I think are likely to happen:
1. Developing a pipeline on a subset of the data for quick iteration. A model with categorical variables will fail when evaluating on the full dataset, as it has not seen all the categorical variables. (Can be fixed with out of vocabulary setting in [tft.compute_and_apply_vocabulary](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/compute_and_apply_vocabulary), but that is not ideal.)
2. Changing serving signatures causes evalution to fail.
3. Changing the name(s) of the output layer(s) causes evaluation to fail.

When all the development bugs are ironed out, it would be great to start a new pipeline run and force a blessing of the newly trained model, instead of literally being stuck in the past with previously blessed models who will fail upon evaluation.

**Will this change the current API? How?**
Not necessarily, if there is a way to force a blessing through existing mechanisms that I am not aware of. However, a simple input flag `force_blessing = True` to the Evaluator component would suffice.

**Who will benefit with this feature?**
Developers of pipelines, both beginners and advanced, who want to change properties of their models and input data during development.

**Do you have a workaround or are completely blocked by this?** :
The omission of a baseline model does not create a blessing, but allows the Evaluator to succeed. The only workaround I have found is to create an entirely new pipeline, which is a bit cumbersome, as you lose any cached components.

**Comment by singhniraj08** [comment]
@axeltidemann,

Blessing by default might be desired, but can be dangerous since a user might forget to set any threshold and a bad model is pushed by accident.  Default Unblessing is safer, but it leads to a no-op, since the model won't be pushed anyway. And again, this makes the multi-evaluators + model validators blessing reasoning unnecessarily complicated and needs an extra layer of logic to reason about the final outcomes of the blessing, which is a lot more complex and can lead to unintended behavior.

So the safer workaround is to add a value threshold to your config (i.e. something simple like example_count > 0), where values of example_count < -1 (trivially unbless) or example_count > 0 (trivially bless) can bless or unbless the model respectively.
Thank you!

Thank you!

**Comment by axeltidemann** [comment]
OK, if it goes against the design choices of TFX, I am happy to close this issue. I agree, you might accidentally shoot yourself in the foot if there is a "force blessing" argument.
