### ISSUE TITLE
Helper function to detect which runner the component is using

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tfx#4682]
**System information**

- TFX Version (you are using): 1.4.1
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): Local, KubeFlow, Interactive
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

To detect the runner in the component, we have to pass a custom parameter that includes the runner information for now.

For example, if I want to handle accessing to a local disk differently in LocalDagRunner and KubeFlowDagRunner in the custom component, I have to know which runner, but I have to modify it to get a custom parameter.

**Will this change the current API? How?**

I think this request won't change existing APIs, but will add a new helper function like `tfx.v1.utils.___utils.get_runner_type`.

**Who will benefit with this feature?**

The people who want to use runner-specific features.

In my case, I want to update my custom component to visualize only in KubeFlow UI (that is related to https://github.com/tensorflow/tfx/pull/4674) via writing a file to `/mlpipeline-ui-metadata.json`. For that feature, I think I have to know which runner I am using in runtime, so I can choose whether to visualize or not.

**Do you have a workaround or are completely blocked by this?** :

Not blocked.
I don't think this is a critical feature in my case, so I can wait to solve this.

**Name of your Organization (Optional)**

**Any Other info.**

I wrote a topic for this issue in TensorFlow Forum, but I got a response that I have to pass a custom parameter to detect it.

https://discuss.tensorflow.org/t/how-can-i-know-which-runner-that-im-using-in-tfx/7631

**Comment by jiyongjung0** [comment]
I think that this is only useful (and usable) for function based custom component. For example, container based components might not have tfx (or Python) in it. 

However, this is needed even in standard components. So there is [an internal utility function to check whether they are in 
 Kubeflow Pipelines](https://github.com/tensorflow/tfx/blob/8785c6eebdcaa5ab84d14477bcad74735c4c59c7/tfx/utils/kube_utils.py#L232).

We might need to define some protocol to pass orchestration information to component level first, because there is no good way to pass information to the component level and , in theory, pipelines can be nested(a custom component can have a local pipeline in it...).

CC @polydier1 @chongkong

**Comment by pindinagesh** [comment]
@jeongukjae 

Could you please close this issue if it's resolved your blockage or can we keep this issue open for other use cases also?

**Comment by jeongukjae** [comment]
@pindinagesh 
It is okay to close this issue.
Thanks :)
