### ISSUE TITLE
https://pypi-nightly.tensorflow.org can't install nightly packages

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#4835]
TFX nightly pypi repository (https://pypi-nightly.tensorflow.org/) seems to be down and has been for at least a week.

Are you working on this or have you moved the nightly builds somewhere else?

**Comment by ConverJens** [comment]
Ping @jiyongjung0 Any info about this?

**Comment by jiyongjung0** [comment]
@ConverJens Thank you for the report!

Yes, we have changed the backend of the pypi repository about 2 weeks ago, and it should be transparent for most of users. But it seems not.. Could you share the particular commands/behavior that was broken?

We are aware of that we have lost the root page ( https://pypi-nightly.tensorflow.org/ )
But you can still browse packages individually like https://pypi-nightly.tensorflow.org/simple/tfx

**Comment by jiyongjung0** [comment]
Actually, I found that our example command at the [guide](https://www.tensorflow.org/tfx/guide) is wrong. (I'm not sure how it worked until now. Maybe there was some fallback mechanism in the previous repository.)

Please use `--extra-index-url` instead of `-i`(which means index-url). Because we need to install packages from the regular pypi.

For the detail, we used [pypicloud](https://pypicloud.readthedocs.io/en/latest/) for the repository, but we migrated to [GCP artifact registry](https://cloud.google.com/artifact-registry).

**Comment by ConverJens** [comment]
@jiyongjung0 Verified. Changing
`python3 -m pip install -i https://pypi-nightly.tensorflow.org/simple/ tfx-bsl` to
`python3 -m pip install --extra-index-url https://pypi-nightly.tensorflow.org/simple/ tfx-bsl` worked.
Thanks!
