### ISSUE TITLE
PrestoExampleGen missing values

### ISSUE THREAD

**Issue by SoheilMehrani** [tensorflow/tfx#5040]
Although there is no problem in data and query, PrestoExampleGen generates missing values (some rows of data will be lost).

```
...
context = InteractiveContext()

presto_config = presto_config_pb2.PrestoConnConfig(
    host=PRESTO_HOST,
    port=PRESTO_PORT,
    user=PRESTO_USER,
    catalog=PRESTO_CATALOG
)

example_gen = PrestoExampleGen(presto_config, query=query)
context.run(example_gen)

statistics_gen = StatisticsGen(examples=example_gen.outputs['examples'])
context.run(statistics_gen)

context.show(statistics_gen.outputs['statistics'])
...
```
![screenshot](https://user-images.githubusercontent.com/36539586/179359149-57d9351e-20de-4c62-9603-8c1ddb13220d.png)

**Comment by singhniraj08** [comment]
@SoheilMehrani,

I was not able to replicate this issue since the data source was not available, can you please try to setup PrestoExampleGen as shown in this [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/custom_components/presto_example_gen/example/taxi_pipeline_presto.py) with latest [TFX release](https://github.com/tensorflow/tfx/releases/tag/v1.12.0).

Thank you!
