### ISSUE TITLE
tfx tuner component keeps running permanently on Vertex Pipelines.

### ISSUE THREAD

**Issue by hugoferrero** [tensorflow/tfx#5607]
Hi. I'm running a TFX pipeline on Vertex AI Pipelines service. When the running gets to the "tuner" component, the job keeps running permenently. Intentionaly "max_trials" parameter is set to "2", but the job kepps going more than 2 hours (Image Below) and also have "Early Stopping". Nothing strange appears in logs just "Job is running"

![Captura de pantalla de 2022-12-21 14-27-13](https://user-images.githubusercontent.com/34080955/209202018-25d2e3e8-be83-4adf-98a6-a8822aeaf99f.png)

This is my setup:
TensorFlow version: 2.10.1
TFX version: 1.11.0
KFP version: 1.8.16

This is the pipeline (Complete code is in https://github.com/hugoferrero/tfx_components) . I'm following this reference: https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_kubeflow.py. Thanks in advance.

```python
ai_platform_training_args = {
     'project': GOOGLE_CLOUD_PROJECT,
     'worker_pool_specs': [{
     'machine_spec': {
     'machine_type': 'n1-standard-4',
                      },
     'replica_count': 1,
     'container_spec': {
     'image_uri': PIPELINE_IMAGE
                        }
                          }]
                               } 
```
``` python
def create_pipeline(
    pipeline_name: str,
    pipeline_root: str,
    query_train: str,
    query_test: str,
    run_fn: str,
    region:str,
    tuner_fn: str,
    tuner_dir: str ,
    serving_model_dir: str,
    ai_platform_training_args: Optional[Dict[str, str]] = None,
    beam_pipeline_args: Optional[List[str]] = None
) -> tfx.dsl.Pipeline:

  # ExampleGen Component
  
  input_config = example_gen_pb2.Input(splits=[
                 example_gen_pb2.Input.Split(name='train', pattern=query_train),
                 example_gen_pb2.Input.Split(name='eval', pattern=query_test)
                               ])

  example_gen = tfx.extensions.google_cloud_big_query.BigQueryExampleGen(
      input_config=input_config
      )
  
  # StatisticsGen Component

  statistics_gen = tfx.components.StatisticsGen(examples=example_gen.outputs['examples'])

  
  # SchemaGem Component

  schema_gen = tfx.components.SchemaGen(statistics=statistics_gen.outputs['statistics'])
  
  # Tuner Component
  
  tuner = tfx.extensions.google_cloud_ai_platform.Tuner(
        tuner_fn=tuner_fn,
        examples=example_gen.outputs['examples'],
        schema = schema_gen.outputs['schema'],
        train_args=tfx.proto.TrainArgs(num_steps=20),
        eval_args=tfx.proto.EvalArgs(num_steps=5),
        custom_config = {
        tfx.extensions.google_cloud_ai_platform.ENABLE_VERTEX_KEY: True,
        tfx.extensions.google_cloud_ai_platform.VERTEX_REGION_KEY: region,
        tfx.extensions.google_cloud_ai_platform.experimental.TUNING_ARGS_KEY:
            ai_platform_training_args,
        tfx.extensions.google_cloud_ai_platform.experimental.REMOTE_TRIALS_WORKING_DIR_KEY:
                  os.path.join(tuner_dir, 'trials')    
                        }
        )

  # Trainer Component

  trainer = tfx.extensions.google_cloud_ai_platform.Trainer(
       run_fn = run_fn,
       examples = example_gen.outputs['examples'],
       schema = schema_gen.outputs['schema'],
       hyperparameters=tuner.outputs['best_hyperparameters'],
       train_args=tfx.proto.TrainArgs(num_steps=20),
       eval_args=tfx.proto.EvalArgs(num_steps=5),
       custom_config = {
        tfx.extensions.google_cloud_ai_platform.ENABLE_VERTEX_KEY: True,
        tfx.extensions.google_cloud_ai_platform.VERTEX_REGION_KEY: region,
        tfx.extensions.google_cloud_ai_platform.TRAINING_ARGS_KEY:
            ai_platform_training_args
                        }
                        )
                        
 
  pusher = tfx.components.Pusher(
      model=trainer.outputs['model'],
      push_destination=tfx.proto.PushDestination(
      filesystem=tfx.proto.PushDestination.Filesystem(
      base_directory=serving_model_dir)))
  
  components = [
      example_gen,
      statistics_gen,
      schema_gen,
      tuner,
      trainer,
      pusher
            ] 

  return tfx.dsl.Pipeline(
      pipeline_name=pipeline_name,
      pipeline_root=pipeline_root,
      components=components,
      beam_pipeline_args=beam_pipeline_args)


```

**Comment by singhniraj08** [comment]
@hugoferrero,

Can you try using `tune_args=tfx.proto.TuneArgs(num_parallel_trials=3),` in tuner component for parallel processing as shown [here](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_kubeflow.py#L305-L324). `num_parallel_trials=3` means that 3 search loops are running in parallel and will led to faster execution.

You can also try multi-worker distribution training for each trial using [DistributingCloudTuner](https://github.com/tensorflow/cloud/blob/b9c8752f5c53f8722dfc0b5c7e05be52e62597a8/src/python/tensorflow_cloud/tuner/tuner.py#L384-L676) instead of CloudTuner. DistributingCloudTuner(a subclass of CloudTuner) launches remote distributed training job per trial.

Please refer [here](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_kubeflow.py#L261-L278) for more info on parallel tuning and distributed tuning. Thank you!

**Comment by hugoferrero** [comment]
Hi @singhniraj08 . Thanks for reply. I did what you suggested and and the issue remains anyway. I stopped the job after 6:29 hours of running. The same hyperparameter setting, without tfx components, running in Vertex "Training" service, takes no longer than 30 minutes, with machine type 'n1-standard-4' and no distribution strategy. 
![Captura de pantalla de 2023-01-10 17-35-18](https://user-images.githubusercontent.com/34080955/211661301-ba8d9554-27ef-4fb2-82f9-7bcaab831b0b.png)

**Comment by 1025KB** [comment]
are you able to run penguin_pipeline_kubeflow.py without issue?

**Comment by hugoferrero** [comment]
Hi @1025KB , sorry for the delay. Yes I was able to run the penguin_pipeline_kubeflow.py withou any issues. The problem comes when i use `tfx.extensions.google_cloud_ai_platform.Trainer` component, `tfx.v1.components.Tuner` component works fine in my use case,  ... I can't  find  any clue on logs because Job keeps on runing on an infinite loop.

**Comment by EdwardCuiPeacock** [comment]
I have got a similar issue with `tfx.extensions.google_cloud_ai_platform.Tuner`. In my case, I have a bug in the `tuner_fn` which results an error in my tuning process (which I identified through the logs). However, the tuner component job instance does not fail but it hangs there for hours. I recall I filed a (similar issue)[https://github.com/tensorflow/tfx/issues/4419] on the Trainer component as well in the past, but I am not sure this is related to that.

**Comment by singhniraj08** [comment]
Hi @hugoferrero,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFX team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFX [version](https://pypi.org/project/tfx/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfx/releases) to stay up to date with the latest developments which are happening in the TFX  space. 
Thank you!
