### ISSUE TITLE
`Empty` Component

### ISSUE THREAD

**Issue by valeriano-manassero** [tensorflow/tfx#573]
I'm looking for a way to get an "empty" component that simply start a function from an `utils.py` file.

I'm aiming to use a component like that to download and extract data before using an `ImportExampleGen` on them, or to convert a model to Lite version after I got it pushed by a `Pusher`.

I think there can be a lot of use cases for that.
There's an easy way to achieve this or I need to write a complete new custom component?

wdyt?

**Comment by robertlugg** [comment]
Could you do this by creating a "trigger", for lack of a better term?  Create a channel that doesn't move data but instead moves a boolean in and out of your component.  This would allow it to be included in your pipeline and be called at the right time.

**Comment by valeriano-manassero** [comment]
I tried this solution without success so I was wondering if a custom Executor can be the solution, btw I'm still stuck ( https://github.com/tensorflow/tfx/issues/583 ).
Thank you for your support, I will investigate further.

**Comment by ruoyu90** [comment]
@valeriano-manassero @robertlugg thanks for the feedback!

> I'm aiming to use a component like that to download and extract data before using an `ImportExampleGen` on them

Seems this can be solved by custom executor in `ImportExampleGen` if the component interface stays the same. Otherwise, a custom component might be needed.

> or to convert a model to Lite version after I got it pushed by a `Pusher`

Assuming you'll want the Lite version model to be an output of a component? In this case, you'll need to compose a custom component to take trainer's output (model_export) and convert that into a lite version model.

**Comment by valeriano-manassero** [comment]
Thank you for pointing me to the right direction, I'm going to try new implementations based on your suggestions.
