### ISSUE TITLE
TFX pipeline Local orchestrator documentation site contains several errors/exceptions

### ISSUE THREAD

**Issue by ruan-takealot** [tensorflow/tfx#6344]
The document covering the usage of the TFX pipeline Local orchestrator currently has many errors/exceptions on it.

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/tutorials/tfx/template_local
(snapshot at time of issue creation: https://web.archive.org/web/20230930160141/https://www.tensorflow.org/tfx/tutorials/tfx/template_local)

## Description of issue (what needs changing):

At the time of issue creation, the text in the output sections of the documentation contains many errors or exception messages.
Examples:
* `tensorflow.python.framework.errors_impl.PermissionDeniedError: /content; Permission denied`
* `/tmpfs/src/tf_docs_env/bin/python: Error while finding module specification for 'models.features_test' (ModuleNotFoundError: No module named 'models')`
* `Invalid pipeline path: local_runner.py`
* (several times) `/tmpfs/src/tf_docs_env/bin/python3.9: can't open file '/tmpfs/src/temp/docs/tutorials/tfx/local_runner.py': [Errno 2] No such file or directory. Error while running "/tmpfs/src/tf_docs_env/bin/python3.9 local_runner.py"`

### Clear description:

The document documenting the usage of the TFX pipeline Local orchestrator currently has many errors/exceptions on it.

### Correct links

N/A

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

N/A

### Request visuals, if applicable

![image](https://github.com/tensorflow/tfx/assets/49143733/bc04bf24-5993-4df5-a8e8-fafd1f0f6fa4)

**Comment by singhniraj08** [comment]
@ruan-takealot,

I tried the [template_local](https://www.tensorflow.org/tfx/tutorials/tfx/template_local) example in colab environment and it ran successfully without any issues. Ref: [Gist](https://colab.research.google.com/gist/singhniraj08/3d3f37c1ae9ff24c8b417197e993e5e1/copy-of-template_local.ipynb)

Only error I was able to see was `(ModuleNotFoundError: No module named 'models.keras')` in the pipeline unit test. Let me debug this and I will update the thread on unit test failure. Apart from that the pipeline runs successfully without any issues.

The permission denied error you are facing is most probably because you may not have permissions to write/read in your working directory. Using `sudo` to run commands with root privileges or making sure you working directory is correct will resolve this issue. Ref: similar issue [tensorflow/issues/6393](https://github.com/tensorflow/tensorflow/issues/6393)

Thank you!

**Comment by ruan-takealot** [comment]
Thanks @singhniraj08. I'm looking forward to seeing the public-facing documentation in a fixed state :slightly_smiling_face:

**Comment by singhniraj08** [comment]
@ruan-takealot,

Above merged PR #6358 should address the issue with unit test cases and I see documentation is also updated. Please try once and let us know if you face nay issues. Thank you!

**Comment by ruan-takealot** [comment]
Looks like the public (internet-facing) documentation still contains errors:
  
![image](https://github.com/tensorflow/tfx/assets/49143733/aa10e9d3-6cda-4cbf-bd04-68b9a40c01c2)
  
Do you have to run something else after you merged the PR to update the public documentation?

**Comment by singhniraj08** [comment]
@ruan-takealot,

In which environment are you running the code? I tried running the code in colab environment and it ran without any Permission denied errors. Ref: [Gist](https://colab.research.google.com/gist/singhniraj08/3d3f37c1ae9ff24c8b417197e993e5e1/copy-of-template_local.ipynb)

If you are seeing the error in colab environment, requesting you to create a github gist, and share the notebook with us for this error. Thank you!

**Comment by ruan-takealot** [comment]
@singhniraj08 
The issue isn't running the code. The issue is the public facing HTML documentation.
Currently, this is what someone who has a internet browser sees on the public documentation:

![image](https://github.com/tensorflow/tfx/assets/49143733/dcd7ceb4-4b19-4208-9a94-74bf34ab0943)

**Comment by ruan-takealot** [comment]
I suspect this issue won't be addressed any time soon :disappointed:
There are many TFX HTML documents (not only on this topic) that are full of errors in their cell outputs.
