### ISSUE TITLE
Using TFX components with TF 1.x contrib ops

### ISSUE THREAD

**Issue by misterpeddy** [tensorflow/tfx#838]
Due to the deprecation of TF contrib ops, any SavedModel produced using contrib ops (or indirectly using for example, tf.Transform ops that used tf.contrib ops underneath the hood such as tft.quantiles, tft.bucketize, etc.) cannot be loaded with TF 2.0. 
Is there a migration story for users beyond rewriting our models to use TF core ops?

**Comment by zhitaoli** [comment]
I would think this is more of a tensorflow question, and @martinwicke or @karmel can probably give some better guidance.

Specifically, I wonder whether there is a list of ops which were previously in contrib but removed in TF 2.0, and where can users find their replacements.

**Comment by unclepeddy** [comment]
There's been a bunch of documentation published by TF ([ex](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md)).

More than providing more solutions, this issue aims to be used as a means of recording problems of TFX users who come to us with issues concerning contrib ops deprecation so that we can track them in a central issue.

**Comment by martinwicke** [comment]
I never made a list of ops, but the RFC (https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) contains a list of what happened to which projects.
 
Many ops moved to core or addons or io, although the ops which were used only in TFT wouldn't have been moved elsewhere.

**Comment by gowthamkpr** [comment]
Is it still an issue? As tensorflow does not officially support contib anymore, can we go ahead and close this issue. Thanks!

**Comment by gowthamkpr** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
