### ISSUE TITLE
Iterating TFRecordDataset Gives Only First Row of Data

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tfx#917]
After performing a simple TFT operation, trying to see the results by decoding a TFRecordDataset using TFExampleDecoder ONLY gives you the FIRST row of the data and its transformations. In other words, when attempting to iterate over this TFRecordDataset, it shows that only the first row exists (none of the transformation functions were aggregate operations).

Is this an issue? Or is there a different way of iterating over TFRecordDataset that is not shown in the available docs?

Here is an exact replica of the issue, using Colab:
https://colab.research.google.com/drive/1Y65taeKbI5QFcYHpY6toDLRJ1RLpciIt

**Comment by 1025KB** [comment]
did you check the tfrecord to see how many rows in it? [here](https://stackoverflow.com/questions/40472139/obtaining-total-number-of-records-from-tfrecords-file-in-tensorflow) is some examples about checking row count in tfrecord, both python io way and TFRecordDataset way

**Comment by luischinchillagarcia** [comment]
Yes, it seems the data is store inside. It just iterating over the decoded example that causes the issue.
 
Calling 'next' after setting it as an iterator shows that only the first row exists. This is inconsistent to the behavior found while iterating over any other tf.Records example.

**Comment by 1025KB** [comment]
Sorry I don't quite understand the issue here

for tfrecord in dataset:  <- do you mean this only get one row?
  serialized_example = tfrecord.numpy()
  example = decoder.decode(serialized_example) <- or you mean sth happens here?

in our taxi example, tfrecorddataset works fine for getting tf examples from gzip tf record file, here is the [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py#L81)
