### ISSUE TITLE
ChannelParameter does not retain the type

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tfx#918]
ChannelParameter does not retain the type argument passed to it.
This makes retrieving the real type from ComponentSpec instance impossible.

**Comment by rmothukuru** [comment]
@Ark-kun,
Can you please elaborate the issue. 

Also, Please provide details about what platform you are using (operating system, architecture). 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ruoyu90** [comment]
As for now, `Channel` contains type info: https://github.com/tensorflow/tfx/blob/r0.26.0/tfx/types/channel.py
